# Generated by Django 5.0.9 on 2024-11-29 14:26

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0121_customfield_related_object_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('object_id', models.PositiveIntegerField()),
                ('zabbix_model', models.CharField(max_length=30)),
                ('zabbix_id', models.PositiveIntegerField(unique=True)),
                ('zabbix_name', models.CharField(max_length=256, unique=True)),
                ('status', models.CharField(max_length=30)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ['device', 'tenant', 'site', 'platform']}, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'db_table': 'reletionship',
                'ordering': ('content_type', 'status'),
            },
        ),
    ]
